/* =========================================================
   SQLServer Lab 04 - Stored procedures
   All hashing, RSA encryption and RSA decryption are done on client.
   ========================================================= */
USE QLSVNhom;
GO

IF OBJECT_ID('SP_INS_PUBLIC_ENCRYPT_NHANVIEN','P') IS NOT NULL
    DROP PROCEDURE SP_INS_PUBLIC_ENCRYPT_NHANVIEN;
GO
CREATE PROCEDURE SP_INS_PUBLIC_ENCRYPT_NHANVIEN
    @MANV  VARCHAR(20),
    @HOTEN NVARCHAR(100),
    @EMAIL VARCHAR(100),
    @LUONG VARBINARY(MAX),
    @LUONG_ADMIN VARBINARY(MAX),
    @TENDN NVARCHAR(100),
    @MK    VARBINARY(20),
    @PUB   NVARCHAR(MAX),
    @VAITRO VARCHAR(20) = 'NHANVIEN',
    @MANV_LOGIN VARCHAR(20) = NULL
AS
BEGIN
    SET NOCOUNT ON;

    IF (@MANV IS NULL OR LTRIM(RTRIM(@MANV)) = '')
       OR (@HOTEN IS NULL OR LTRIM(RTRIM(@HOTEN)) = '')
       OR (@TENDN IS NULL OR LTRIM(RTRIM(@TENDN)) = '')
       OR (@MK IS NULL) -- VARBINARY không dùng LTRIM được
       OR (@PUB IS NULL OR LTRIM(RTRIM(@PUB)) = '')
    BEGIN
        RAISERROR(N'Dữ liệu đầu vào không được để trống (NULL). Vui lòng kiểm tra lại.', 16, 1);
        RETURN;
    END

    IF EXISTS (SELECT 1 FROM NHANVIEN)
       AND NOT EXISTS (SELECT 1 FROM NHANVIEN WHERE MANV = @MANV_LOGIN AND VAITRO = 'ADMIN')
    BEGIN
        RAISERROR(N'Chỉ admin mới có quyền thêm nhân viên có lương.', 16, 1);
        RETURN;
    END

    INSERT INTO NHANVIEN(MANV, HOTEN, EMAIL, LUONG, LUONG_ADMIN, TENDN, MATKHAU, PUBKEY, VAITRO)
    VALUES (@MANV, @HOTEN, @EMAIL, @LUONG, @LUONG_ADMIN, @TENDN, @MK, @PUB, @VAITRO);
END
GO

IF OBJECT_ID('SP_REGISTER_NHANVIEN','P') IS NOT NULL
    DROP PROCEDURE SP_REGISTER_NHANVIEN;
GO
CREATE PROCEDURE SP_REGISTER_NHANVIEN
    @MANV  VARCHAR(20),
    @HOTEN NVARCHAR(100),
    @EMAIL VARCHAR(100),
    @TENDN NVARCHAR(100),
    @MK    VARBINARY(20),
    @PUB   NVARCHAR(MAX)
AS
BEGIN
    SET NOCOUNT ON;

    INSERT INTO NHANVIEN(MANV, HOTEN, EMAIL, LUONG, TENDN, MATKHAU, PUBKEY, VAITRO)
    VALUES (@MANV, @HOTEN, @EMAIL, NULL, @TENDN, @MK, @PUB, 'NHANVIEN');
END
GO

IF OBJECT_ID('SP_SEL_PUBLIC_ENCRYPT_NHANVIEN','P') IS NOT NULL
    DROP PROCEDURE SP_SEL_PUBLIC_ENCRYPT_NHANVIEN;
GO
CREATE PROCEDURE SP_SEL_PUBLIC_ENCRYPT_NHANVIEN
    @TENDN NVARCHAR(100),
    @MK    VARBINARY(20)
AS
BEGIN
    SET NOCOUNT ON;

    SELECT MANV, HOTEN, EMAIL, LUONG, PUBKEY, VAITRO
    FROM NHANVIEN
    WHERE TENDN = @TENDN
      AND MATKHAU = @MK;
END
GO

IF OBJECT_ID('SP_LOGIN_NHANVIEN','P') IS NOT NULL
    DROP PROCEDURE SP_LOGIN_NHANVIEN;
GO
CREATE PROCEDURE SP_LOGIN_NHANVIEN
    @MANV VARCHAR(20),
    @MK   VARBINARY(20)
AS
BEGIN
    SET NOCOUNT ON;

    SELECT MANV, HOTEN, EMAIL, LUONG, PUBKEY, VAITRO
    FROM NHANVIEN
    WHERE MANV = @MANV
      AND MATKHAU = @MK;
END
GO

IF OBJECT_ID('SP_SEL_NHANVIEN_ALL','P') IS NOT NULL
    DROP PROCEDURE SP_SEL_NHANVIEN_ALL;
GO
CREATE PROCEDURE SP_SEL_NHANVIEN_ALL
AS
BEGIN
    SET NOCOUNT ON;

    SELECT MANV, HOTEN, EMAIL, LUONG, LUONG_ADMIN, TENDN, PUBKEY, VAITRO
    FROM NHANVIEN
    ORDER BY MANV;
END
GO

IF OBJECT_ID('SP_UPD_NHANVIEN_LUONG','P') IS NOT NULL
    DROP PROCEDURE SP_UPD_NHANVIEN_LUONG;
GO
CREATE PROCEDURE SP_UPD_NHANVIEN_LUONG
    @MANV VARCHAR(20),
    @LUONG VARBINARY(MAX),
    @LUONG_ADMIN VARBINARY(MAX),
    @MANV_LOGIN VARCHAR(20)
AS
BEGIN
    SET NOCOUNT ON;

    IF NOT EXISTS (SELECT 1 FROM NHANVIEN WHERE MANV = @MANV_LOGIN AND VAITRO = 'ADMIN')
    BEGIN
        RAISERROR(N'Chỉ admin mới có quyền nhập hoặc thay đổi lương.', 16, 1);
        RETURN;
    END

    UPDATE NHANVIEN SET LUONG = @LUONG, LUONG_ADMIN = @LUONG_ADMIN WHERE MANV = @MANV;
END
GO

IF OBJECT_ID('SP_SEL_NHANVIEN_PUBLICKEY','P') IS NOT NULL
    DROP PROCEDURE SP_SEL_NHANVIEN_PUBLICKEY;
GO
CREATE PROCEDURE SP_SEL_NHANVIEN_PUBLICKEY
    @MANV VARCHAR(20)
AS
BEGIN
    SET NOCOUNT ON;

    SELECT PUBKEY
    FROM NHANVIEN
    WHERE MANV = @MANV;
END
GO

IF OBJECT_ID('SP_SEL_ADMIN_PUBLICKEY','P') IS NOT NULL
    DROP PROCEDURE SP_SEL_ADMIN_PUBLICKEY;
GO
CREATE PROCEDURE SP_SEL_ADMIN_PUBLICKEY
AS
BEGIN
    SET NOCOUNT ON;

    -- Lấy public key của admin đầu tiên (ORDER BY MANV) để mã hóa LUONG_ADMIN
    SELECT TOP 1 PUBKEY
    FROM NHANVIEN
    WHERE VAITRO = 'ADMIN'
    ORDER BY MANV;
END
GO

IF OBJECT_ID('SP_SEL_HOCPHAN','P') IS NOT NULL
    DROP PROCEDURE SP_SEL_HOCPHAN;
GO
CREATE PROCEDURE SP_SEL_HOCPHAN
AS
BEGIN
    SET NOCOUNT ON;

    SELECT MAHP, TENHP, SOTC
    FROM HOCPHAN
    ORDER BY MAHP;
END
GO

IF OBJECT_ID('SP_INS_HOCPHAN','P') IS NOT NULL
    DROP PROCEDURE SP_INS_HOCPHAN;
GO
CREATE PROCEDURE SP_INS_HOCPHAN
    @MAHP VARCHAR(20),
    @TENHP NVARCHAR(100),
    @SOTC INT,
    @MANV_LOGIN VARCHAR(20) = NULL
AS
BEGIN
    SET NOCOUNT ON;

    IF (@MAHP IS NULL OR LTRIM(RTRIM(@MAHP)) = '')
       OR (@TENHP IS NULL OR LTRIM(RTRIM(@TENHP)) = '')
       OR (@SOTC IS NULL OR LTRIM(RTRIM(@SOTC)) = '')
    BEGIN
        RAISERROR(N'Dữ liệu đầu vào không được để trống (NULL). Vui lòng kiểm tra lại.', 16, 1);
        RETURN;
    END

    -- Chỉ admin mới được thêm/sửa học phần (cho qua khi DB chưa có nhân viên để seed lần đầu).
    IF EXISTS (SELECT 1 FROM NHANVIEN)
       AND NOT EXISTS (SELECT 1 FROM NHANVIEN WHERE MANV = @MANV_LOGIN AND VAITRO = 'ADMIN')
    BEGIN
        RAISERROR(N'Chỉ admin mới có quyền thêm hoặc sửa học phần.', 16, 1);
        RETURN;
    END

    IF EXISTS (SELECT 1 FROM HOCPHAN WHERE MAHP = @MAHP)
        UPDATE HOCPHAN SET TENHP = @TENHP, SOTC = @SOTC WHERE MAHP = @MAHP;
    ELSE
        INSERT INTO HOCPHAN(MAHP, TENHP, SOTC) VALUES (@MAHP, @TENHP, @SOTC);
END
GO

IF OBJECT_ID('SP_SEL_LOP_ALL','P') IS NOT NULL
    DROP PROCEDURE SP_SEL_LOP_ALL;
GO
CREATE PROCEDURE SP_SEL_LOP_ALL
AS
BEGIN
    SET NOCOUNT ON;

    SELECT L.MALOP, L.TENLOP, L.MANV, NV.HOTEN AS TEN_GVCN, L.MASV, L.MAHP
    FROM LOP L
    LEFT JOIN NHANVIEN NV ON NV.MANV = L.MANV
    ORDER BY L.MALOP;
END
GO

IF OBJECT_ID('SP_INS_LOP','P') IS NOT NULL
    DROP PROCEDURE SP_INS_LOP;
GO
CREATE PROCEDURE SP_INS_LOP
    @MALOP VARCHAR(20),
    @TENLOP NVARCHAR(100),
    @MANV VARCHAR(20),
    @MAHP VARCHAR(20) = NULL,
    @MANV_LOGIN VARCHAR(20) = NULL
AS
BEGIN
    SET NOCOUNT ON;

    IF (@MALOP IS NULL OR LTRIM(RTRIM(@MALOP)) = '')
       OR (@TENLOP IS NULL OR LTRIM(RTRIM(@TENLOP)) = '')
       OR (@MANV IS NULL OR LTRIM(RTRIM(@MANV)) = '')
       OR (@MAHP IS NULL OR LTRIM(RTRIM(@MAHP)) = '')
    BEGIN
        RAISERROR(N'Dữ liệu đầu vào không được để trống (NULL). Vui lòng kiểm tra lại.', 16, 1);
        RETURN;
    END

    -- Chỉ admin mới được tạo lớp (cho qua khi DB chưa có nhân viên để seed lần đầu).
    IF EXISTS (SELECT 1 FROM NHANVIEN)
       AND NOT EXISTS (SELECT 1 FROM NHANVIEN WHERE MANV = @MANV_LOGIN AND VAITRO = 'ADMIN')
    BEGIN
        RAISERROR(N'Chỉ admin mới có quyền tạo lớp.', 16, 1);
        RETURN;
    END

    INSERT INTO LOP(MALOP, TENLOP, MANV, MAHP)
    VALUES (@MALOP, @TENLOP, @MANV, @MAHP);
END
GO

IF OBJECT_ID('SP_UPD_LOP','P') IS NOT NULL
    DROP PROCEDURE SP_UPD_LOP;
GO
CREATE PROCEDURE SP_UPD_LOP
    @MALOP VARCHAR(20),
    @TENLOP NVARCHAR(100),
    @MANV VARCHAR(20),
    @MAHP VARCHAR(20) = NULL,
    @MANV_LOGIN VARCHAR(20)
AS
BEGIN
    SET NOCOUNT ON;

    IF NOT EXISTS (SELECT 1 FROM NHANVIEN WHERE MANV = @MANV_LOGIN AND VAITRO = 'ADMIN')
       AND NOT EXISTS (SELECT 1 FROM LOP WHERE MALOP = @MALOP AND MANV = @MANV_LOGIN)
    BEGIN
        RAISERROR(N'Nhân viên đang nhập không có quyền sửa lớp này.', 16, 1);
        RETURN;
    END

    -- Ghi trực tiếp giá trị truyền vào (cho phép xóa rỗng); client đã cảnh báo nếu có ô trống.
    UPDATE LOP
    SET TENLOP = @TENLOP, MANV = @MANV, MAHP = @MAHP
    WHERE MALOP = @MALOP;
END
GO

IF OBJECT_ID('SP_SEL_SV_BY_LOP','P') IS NOT NULL
    DROP PROCEDURE SP_SEL_SV_BY_LOP;
GO
CREATE PROCEDURE SP_SEL_SV_BY_LOP
    @MALOP VARCHAR(20)
AS
BEGIN
    SET NOCOUNT ON;

    SELECT MASV, HOTEN, NGAYSINH, DIACHI, MALOP, TENDN
    FROM SINHVIEN
    WHERE MALOP = @MALOP
    ORDER BY MASV;
END
GO

IF OBJECT_ID('SP_SEL_SV_ALL','P') IS NOT NULL
    DROP PROCEDURE SP_SEL_SV_ALL;
GO
CREATE PROCEDURE SP_SEL_SV_ALL
    @MANV_LOGIN VARCHAR(20)
AS
BEGIN
    SET NOCOUNT ON;

    -- Admin xem toàn bộ sinh viên; nhân viên thường chỉ xem SV thuộc lớp mình phụ trách.
    SELECT SV.MASV, SV.HOTEN, SV.NGAYSINH, SV.DIACHI, SV.MALOP, SV.TENDN
    FROM SINHVIEN SV
    WHERE EXISTS (SELECT 1 FROM NHANVIEN WHERE MANV = @MANV_LOGIN AND VAITRO = 'ADMIN')
       OR EXISTS (SELECT 1 FROM LOP L WHERE L.MALOP = SV.MALOP AND L.MANV = @MANV_LOGIN)
    ORDER BY SV.MALOP, SV.MASV;
END
GO

IF OBJECT_ID('SP_INS_SV','P') IS NOT NULL
    DROP PROCEDURE SP_INS_SV;
GO
CREATE PROCEDURE SP_INS_SV
    @MASV NVARCHAR(20),
    @HOTEN NVARCHAR(100),
    @NGAYSINH DATE,
    @DIACHI NVARCHAR(200),
    @MALOP VARCHAR(20),
    @TENDN NVARCHAR(100),
    @MK VARBINARY(20),
    @MANV_LOGIN VARCHAR(20)
AS
BEGIN
    SET NOCOUNT ON;

    -- 1. KIỂM TRA CÁC GIÁ TRỊ ĐẦU VÀO CÓ BỊ NULL HAY KHÔNG
    -- Bạn có thể bỏ bớt các biến không bắt buộc (ví dụ: DIACHI nếu bảng cho phép NULL)
    IF (@MASV IS NULL OR LTRIM(RTRIM(@MASV)) = '')
       OR (@HOTEN IS NULL OR LTRIM(RTRIM(@HOTEN)) = '')
       OR (@MK IS NULL) -- VARBINARY không dùng LTRIM được
       OR (@MALOP IS NULL OR LTRIM(RTRIM(@MALOP)) = '')
       OR (@TENDN IS NULL OR LTRIM(RTRIM(@TENDN)) = '')
    BEGIN
        RAISERROR(N'Dữ liệu đầu vào không được để trống (NULL). Vui lòng kiểm tra lại.', 16, 1);
        RETURN;
    END

    -- 2. KIỂM TRA PHÂN QUYỀN (Code cũ của bạn)
    IF NOT EXISTS (SELECT 1 FROM NHANVIEN WHERE MANV = @MANV_LOGIN AND VAITRO = 'ADMIN')
    AND NOT EXISTS (SELECT 1 FROM LOP WHERE MALOP = @MALOP AND MANV = @MANV_LOGIN)
    BEGIN
        RAISERROR(N'Nhân viên đang nhập không có quyền thêm sinh viên vào lớp này.', 16, 1);
        RETURN;
    END

    -- 3. THỰC HIỆN INSERT KHI TẤT CẢ ĐIỀU KIỆN ĐÃ HỢP LỆ
    INSERT INTO SINHVIEN(MASV, HOTEN, NGAYSINH, DIACHI, MALOP, TENDN, MATKHAU)
    VALUES (@MASV, @HOTEN, @NGAYSINH, @DIACHI, @MALOP, @TENDN, @MK);
END
GO

IF OBJECT_ID('SP_UPD_SV','P') IS NOT NULL
    DROP PROCEDURE SP_UPD_SV;
GO
CREATE PROCEDURE SP_UPD_SV
    @MASV NVARCHAR(20),
    @HOTEN NVARCHAR(100),
    @NGAYSINH DATE,
    @DIACHI NVARCHAR(200),
    @MANV_LOGIN VARCHAR(20)
AS
BEGIN
    SET NOCOUNT ON;

    IF NOT EXISTS (SELECT 1 FROM NHANVIEN WHERE MANV = @MANV_LOGIN AND VAITRO = 'ADMIN')
       AND NOT EXISTS (
        SELECT 1
        FROM SINHVIEN SV
        JOIN LOP L ON L.MALOP = SV.MALOP
        WHERE SV.MASV = @MASV AND L.MANV = @MANV_LOGIN
    )
    BEGIN
        RAISERROR(N'Nhân viên đang nhập không có quyền sửa sinh viên này.', 16, 1);
        RETURN;
    END

    -- Ghi trực tiếp giá trị truyền vào (cho phép xóa rỗng); client đã cảnh báo nếu có ô trống.
    UPDATE SINHVIEN
    SET HOTEN = @HOTEN, NGAYSINH = @NGAYSINH, DIACHI = @DIACHI
    WHERE MASV = @MASV;
END
GO

IF OBJECT_ID('SP_DEL_SV','P') IS NOT NULL
    DROP PROCEDURE SP_DEL_SV;
GO
CREATE PROCEDURE SP_DEL_SV
    @MASV NVARCHAR(20),
    @HOTEN NVARCHAR(100) = NULL,
    @NGAYSINH DATE = NULL,
    @DIACHI NVARCHAR(200) = NULL,
    @MALOP VARCHAR(20) = NULL,
    @MANV_LOGIN VARCHAR(20)
AS
BEGIN
    SET NOCOUNT ON;

    IF (@MASV IS NULL OR LTRIM(RTRIM(@MASV)) = '')
    BEGIN
        RAISERROR(N'Dữ liệu đầu vào không được để trống (NULL). Vui lòng kiểm tra lại.', 16, 1);
        RETURN;
    END

    IF NOT EXISTS (SELECT 1 FROM NHANVIEN WHERE MANV = @MANV_LOGIN AND VAITRO = 'ADMIN')
       AND NOT EXISTS (
        SELECT 1
        FROM SINHVIEN SV
        JOIN LOP L ON L.MALOP = SV.MALOP
        WHERE SV.MASV = @MASV AND L.MANV = @MANV_LOGIN
    )
    BEGIN
        RAISERROR(N'Nhân viên đang nhập không có quyền xóa sinh viên này.', 16, 1);
        RETURN;
    END

    -- Cascade: gỡ tham chiếu và xóa dữ liệu phụ thuộc trước (BANGDIEM, LOP.MASV) rồi mới xóa SV.
    BEGIN TRY
        BEGIN TRANSACTION;
            UPDATE LOP SET MASV = NULL WHERE MASV = @MASV;
            DELETE FROM BANGDIEM WHERE MASV = @MASV;
            DELETE FROM SINHVIEN WHERE MASV = @MASV;
        COMMIT TRANSACTION;
    END TRY
    BEGIN CATCH
        IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION;
        THROW;
    END CATCH
END
GO

IF OBJECT_ID('SP_INS_BANGDIEM_ENCRYPT','P') IS NOT NULL
    DROP PROCEDURE SP_INS_BANGDIEM_ENCRYPT;
GO
CREATE PROCEDURE SP_INS_BANGDIEM_ENCRYPT
    @MASV NVARCHAR(20),
    @MALOP VARCHAR(20),
    @MAHP VARCHAR(20),
    @DIEMTHI VARBINARY(MAX),
    @MANV_LOGIN VARCHAR(20)
AS
BEGIN
    SET NOCOUNT ON;

    IF (@MASV IS NULL OR LTRIM(RTRIM(@MASV)) = '')
       OR (@MALOP IS NULL OR LTRIM(RTRIM(@MALOP)) = '')
       OR (@MAHP IS NULL OR LTRIM(RTRIM(@MAHP)) = '')
       OR (@DIEMTHI IS NULL)
       OR (@MANV_LOGIN IS NULL OR LTRIM(RTRIM(@MANV_LOGIN)) = '')
    BEGIN
        RAISERROR(N'Dữ liệu đầu vào không được để trống (NULL). Vui lòng kiểm tra lại.', 16, 1);
        RETURN;
    END

    IF NOT EXISTS (SELECT 1 FROM NHANVIEN WHERE MANV = @MANV_LOGIN AND VAITRO = 'ADMIN')
       AND NOT EXISTS (
        SELECT 1
        FROM SINHVIEN SV
        JOIN LOP L ON L.MALOP = SV.MALOP
        WHERE SV.MASV = @MASV AND L.MANV = @MANV_LOGIN
    )
    BEGIN
        RAISERROR(N'Nhân viên đang nhập không có quyền nhập điểm cho sinh viên này.', 16, 1);
        RETURN;
    END

    -- Sinh viên phải thuộc lớp @MALOP và lớp đó phải đúng học phần @MAHP.
    IF NOT EXISTS (
        SELECT 1
        FROM SINHVIEN SV
        JOIN LOP L ON L.MALOP = SV.MALOP
        WHERE SV.MASV = @MASV AND L.MALOP = @MALOP AND L.MAHP = @MAHP
    )
    BEGIN
        RAISERROR(N'Mã lớp hoặc mã học phần không khớp với sinh viên. Vui lòng kiểm tra lại.', 16, 1);
        RETURN;
    END

    IF EXISTS (SELECT 1 FROM BANGDIEM WHERE MASV = @MASV AND MAHP = @MAHP)
        UPDATE BANGDIEM
        SET DIEMTHI = @DIEMTHI, MANV_NHAP = @MANV_LOGIN
        WHERE MASV = @MASV AND MAHP = @MAHP;
    ELSE
        INSERT INTO BANGDIEM(MASV, MAHP, DIEMTHI, MANV_NHAP)
        VALUES (@MASV, @MAHP, @DIEMTHI, @MANV_LOGIN);
END
GO

IF OBJECT_ID('SP_SEL_BANGDIEM_ENCRYPT','P') IS NOT NULL
    DROP PROCEDURE SP_SEL_BANGDIEM_ENCRYPT;
GO
CREATE PROCEDURE SP_SEL_BANGDIEM_ENCRYPT
    @MALOP VARCHAR(20),
    @MAHP VARCHAR(20),
    @MANV_LOGIN VARCHAR(20)
AS
BEGIN
    SET NOCOUNT ON;

    -- Mã học phần phải đúng là học phần của lớp đang tải.
    IF NOT EXISTS (SELECT 1 FROM LOP WHERE MALOP = @MALOP AND MAHP = @MAHP)
    BEGIN
        RAISERROR(N'Mã lớp hoặc mã học phần không khớp. Vui lòng kiểm tra lại.', 16, 1);
        RETURN;
    END

    -- Học phần lấy theo lớp (LOP.MAHP) nên SV chưa có điểm vẫn hiện đủ MAHP/TENHP.
    SELECT SV.MASV, SV.HOTEN, L.MAHP, HP.TENHP, BD.DIEMTHI, BD.MANV_NHAP
    FROM SINHVIEN SV
    JOIN LOP L ON L.MALOP = SV.MALOP
    LEFT JOIN HOCPHAN HP ON HP.MAHP = L.MAHP
    LEFT JOIN BANGDIEM BD ON BD.MASV = SV.MASV AND BD.MAHP = L.MAHP
    WHERE SV.MALOP = @MALOP
      AND (
          EXISTS (SELECT 1 FROM NHANVIEN WHERE MANV = @MANV_LOGIN AND VAITRO = 'ADMIN')
          OR EXISTS (SELECT 1 FROM LOP L2 WHERE L2.MALOP = SV.MALOP AND L2.MANV = @MANV_LOGIN)
      )
    ORDER BY SV.MASV;
END
GO

PRINT N'Created Lab04 stored procedures.';
GO
